name: spo_balaesang
version: 2.0.0+1
publish_to: none
description: Sistem presensi online kantor pemerintahan kecamatan balaesang.
environment: 
  sdk: '>=2.7.0 <3.0.0'

dependencies: 
  font_awesome_flutter: ^9.0.0
  flutter_cupertino_datetime_picker: ^2.0.1
  percent_indicator: ^3.0.1
  table_calendar: ^3.0.0
  cupertino_icons: ^1.0.3
  http: ^0.13.1
  provider: ^5.0.0
  intl: ^0.17.0
  url_launcher: ^6.0.4
  shared_preferences: ^2.0.5
  permission_handler: ^7.1.0
  slugify: ^2.0.0
  device_info: ^2.0.1
  auto_size_text: ^3.0.0-nullsafety.0
  geolocator: ^7.0.3
  android_intent: ^2.0.0
  app_settings: ^4.1.0
  flutter_config: any
  camera: ^0.8.1
  path_provider: ^2.0.1
  path: ^1.8.0
  flutter_image_compress: ^1.0.0
  qr_code_scanner: ^0.4.0
  flutter_countdown_timer: ^4.0.2
  image_picker: ^0.7.4
  geocoding: ^2.0.0
  progress_dialog: ^1.2.4
  shimmer: ^2.0.0-nullsafety.0
  get: ^4.1.1
  flare_flutter: ^3.0.0
  introduction_screen: ^2.1.0
  flutter_launcher_icons: ^0.9.0
  onesignal_flutter: ^2.6.2
  flutter_local_notifications: ^5.0.0
  cached_network_image: ^3.0.0
  photo_view: ^0.11.1
  flutter_native_splash: ^1.1.5+1
  flutter_spinkit: ^5.0.0
  lint: ^1.5.3
  pull_to_refresh: 2.0.0
  timeline_tile: 2.0.0
  search_page: 2.0.0+1
  location: 4.1.1
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_test: 
    sdk: flutter

flutter_icons: 
  image_path_ios: assets/launcher/icon.png
  image_path_android: assets/launcher/icon.png
  adaptive_icon_background: assets/launcher/launcher_bg.png
  adaptive_icon_foreground: assets/launcher/launcher_fg.png
  ios: true
  android: true

flutter_native_splash: 
  image: assets/launcher/icon.png
  color: 6b8eef
  android_disable_fullscreen: true

flutter: 
  assets: 
    - assets/images/
    - assets/logo/
    - assets/flare/
    - assets/launcher/
  uses-material-design: true

