name: spo_balaesang
description: Sistem presensi online kantor pemerintahan kecamatan balaesang.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  font_awesome_flutter: 8.11.0
  flutter_cupertino_date_picker:
    git: https://github.com/daveleenew/flutter-cupertino-date-picker.git
  percent_indicator: 2.1.9
  table_calendar: 2.3.3
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  http: ^0.12.2
  provider: ^4.3.2+2
  intl: ^0.16.1
  url_launcher: ^5.7.2
  shared_preferences: ^0.5.12
  permission_handler: ^5.0.1+1
  slugify: ^1.0.0
  device_info: ^0.4.2+8
  auto_size_text: ^2.1.0
  geolocator: ^5.3.2+2
  android_intent: ^0.3.7+4
  app_settings: ^4.0.4
  flutter_config:
  camera:
  path_provider:
  path:
  flutter_image_compress: ^0.7.0
  qr_code_scanner: ^0.0.12
  flutter_countdown_timer: ^1.4.0
  image_picker: ^0.6.7+14
  geocoding: ^1.0.5
  progress_dialog: ^1.2.4
  shimmer: ^1.0.0
  get:
  flare_flutter: ^2.0.6
  introduction_screen:
  flutter_launcher_icons:
  onesignal_flutter: ^2.6.2
  flutter_local_notifications:
  cached_network_image:
  photo_view:
  flutter_native_splash: 0.1.9
  flutter_spinkit: 4.1.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/launcher/icon.png"
  image_path_android: "assets/launcher/icon.png"
  adaptive_icon_background: "assets/launcher/launcher_bg.png"
  adaptive_icon_foreground: "assets/launcher/launcher_fg.png"

flutter_native_splash:
  image: assets/launcher/icon.png
  android_disable_fullscreen: true
  color: '6b8eef'

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/logo/
    - assets/flare/
    - assets/launcher/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages